Add: save taxi articles in DB
sparcs-kaist/taxi-everytime-crawler pull request #14
Opened 2023-02-01 14:50 UTC by antaechan

It closes #5

2023-02-02 02:41 UTC, 14KGun requested changes
코멘트 반영 부탁드려요 😄

2023-02-08 07:56 UTC, withSang reviewed
감사합니다! 몇 가지 생각나는 것들을 정리해 보았어요.

2023-02-08 07:56 UTC, withSang commented on .env.example
> +port=[port 번호]
DB에 username, password가 지정된 경우도 있어서 hostname과 port로 연결하시는 대신에 connection string을 사용하시는 게 어떨까 합니다.
참조: https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html

2023-02-08 07:56 UTC, withSang commented on crawler.py
> +    local = client['local']
마찬가지로 db 이름이 `'local'`이 아닐 수 있기 때문에 환경변수로 분리하면 더 좋을 거라고 생각해요 ㅎㅎ

2023-02-08 07:56 UTC, withSang commented on crawler.py
> +            context = raw_article.find("p", attrs = {"class":"medium"}).text
코드 포맷팅 관련해서 Black( https://github.com/psf/black )을 사용하는 건 어떨까요?

2023-02-08 07:56 UTC, withSang commented on crawler.py
> +            if len(list(everytime_taxi_articles.find({"id": id}))) == 0:
👍

2023-02-08 12:37 UTC, antaechan commented on crawler.py
> +            if len(list(everytime_taxi_articles.find({"id": id}))) == 0:
감사합니다 한번 고쳐볼께요

2023-02-15 13:34 UTC, withSang commented on .env.example
> +port=[port 번호]
👍

2023-02-15 13:35 UTC, withSang commented on crawler.py
> +    local = client['local']
👍

2023-02-15 13:35 UTC, withSang commented on crawler.py
> +            context = raw_article.find("p", attrs = {"class":"medium"}).text
오 좋아요

2023-02-15 13:38 UTC, withSang approved these changes
감사합니다. 좋아 보여요. 고생 많으셨습니다!! 👍

2023-02-15 13:38 UTC, withSang commented on crawler.py
> +    crawling()
👍

2023-02-15 13:39 UTC, merged