Add: Login
sparcs-kaist/taxi-everytime-crawler pull request #2
Opened 2023-01-11 14:34 UTC by antaechan

It closes #1

2023-01-11 14:41 UTC, withSang requested changes
우왕 로그인 빠르게 잘 짜시다니 대단하세요!! 몇 가지 조심스러운 제안사항 남겨드립니다. 감사합니다!

2023-01-11 14:41 UTC, withSang commented on crawler.py
> +    "userid" : os.getenv('id_antaechan'),
성함이 없는 `everytime_id`와 `everytime_password`도 괜찮아요.

2023-01-11 14:41 UTC, withSang commented on crawler.py
> +url = "https://everytime.kr/user/login"
`login_url`로 변수명이 수정되면 보기 편합니다!

2023-01-11 14:41 UTC, withSang commented on .gitignore
>  chromedriver_win32/
이거는 이제 없어도 됩니다!

2023-01-11 14:41 UTC, withSang commented on .gitignore
>  chromedriver_win32/
또한 크롬드라이버 실행 바이너리가 OS마다 다르기 때문에, 리눅스를 사용하는 실제 배포 환경에서는 크롬드라이버 경로가 달라질 거예요.

2023-01-11 14:53 UTC, antaechan commented on crawler.py
> +    "userid" : os.getenv('id_antaechan'),
수정했습니다

2023-01-11 14:54 UTC, antaechan commented on crawler.py
> +url = "https://everytime.kr/user/login"
@antaechan
[Rename: login_url 변수](https://github.com/sparcs-kaist/taxi-everytime-crawler/pull/2/commits/34bed0a1ffc10af220e039836e8fea185625ef21)

2023-01-11 14:54 UTC, antaechan commented on crawler.py
> +    "userid" : os.getenv('id_antaechan'),
[fb168c4](https://github.com/sparcs-kaist/taxi-everytime-crawler/pull/2/commits/fb168c4d3e1ccfe63b46b0fca9abafdcc16eb84b)

2023-01-11 14:55 UTC, antaechan commented on crawler.py
> +    "userid" : os.getenv('id_antaechan'),
[everytime_id, everytime_password 변수](https://github.com/sparcs-kaist/taxi-everytime-crawler/pull/2/commits/fb168c4d3e1ccfe63b46b0fca9abafdcc16eb84b)
[fb168c4](https://github.com/sparcs-kaist/taxi-everytime-crawler/pull/2/commits/fb168c4d3e1ccfe63b46b0fca9abafdcc16eb84b)

2023-01-11 14:55 UTC, antaechan commented on crawler.py
> +    "userid" : os.getenv('id_antaechan'),
@antaechan
[everytime_id, everytime_password 변수](https://github.com/sparcs-kaist/taxi-everytime-crawler/pull/2/commits/fb168c4d3e1ccfe63b46b0fca9abafdcc16eb84b)

2023-01-11 14:56 UTC, antaechan commented on .gitignore
>  chromedriver_win32/
[Remove: chromedriver_win32 folder](https://github.com/sparcs-kaist/taxi-everytime-crawler/pull/2/commits/b8d38cab07d84efcf4da525e42ffa28d65941550)

2023-01-12 02:31 UTC, 14KGun approved these changes
수고하셨습니다 ~~

이슈 새로 만들어서
1) `requirements.txt` 파일 추가하기 (각 라이브러리 버전도 함께 명시해서)
2) `.env` 파일 예시를 `example.env` 나 `README`에 적기
작업이 진행되면 좋을 것 같아요 ! 👍 😄

2023-01-18 09:36 UTC, merged