Add: requirement.txt
sparcs-kaist/taxi-everytime-crawler pull request #4
Opened 2023-01-18 09:50 UTC by antaechan

It closes #3

2023-01-18 09:52 UTC, withSang approved these changes
감사합니다.

2023-01-18 09:52 UTC, 14KGun commented on requirements.txt
> +kiwisolver==1.4.4
필요한 package 만 명시해주세요 !!

2023-01-18 09:53 UTC, 14KGun requested changes
`bs4`나 `requests` 와 같은 필요한 패키지만 명시해주세요 !

2023-01-18 09:55 UTC, antaechan commented on requirements.txt
> +kiwisolver==1.4.4
requests
beautifulsoup
selenium
일단은 이렇게 3개만 하면 될까요?

2023-01-18 14:37 UTC, 14KGun commented on requirements.txt
> +selenium==4.7.2
`python-dotenv`도 추가되어야 할듯요!

2023-01-25 08:14 UTC, antaechan commented on requirements.txt
> +selenium==4.7.2
[Add: python-dotenv package](https://github.com/sparcs-kaist/taxi-everytime-crawler/pull/4/commits/b40c5a6049fea99ce5a57b1bb06aa848c2ccc21a)

2023-02-01 10:05 UTC, 14KGun approved these changes
LGTM!

2023-02-01 11:39 UTC, merged